---
title: "Untitled"
author: "Aina Nurmagombetova"
date: "25 12 2018"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(remoji)
library(qdapRegex)
library(stringr)
```


```{r}
df_with_all_emojies <- read_csv('full_df_twi_tg.csv')

#удалить emoji
emojis = df_with_all_emojies$emoji
emojis = emojis[!duplicated(emojis)]
df_with_all_emojies$only_texts <-str_replace_all(df_with_all_emojies$texts, paste0(emojis, collapse = '|'), '') 

#удаляем пунткуацию
df_with_all_emojies$only_texts = str_replace_all(df_with_all_emojies$only_texts, "[[:punct:][:blank:]]+", " " )
  

#среднеяя длина сообщения для TWITTER
twi <- df_with_all_emojies %>% filter(source == "Twitter") 
twi <- twi %>% group_by(only_texts, names, time) %>% summarize(count_emojis = n())
twi$word_count <- str_count(twi$only_texts, '\\W+')+1
twi$emoji_word_count = twi$count_emojis + twi$word_count

#только слова
mean(twi$word_count)
sd(twi$word_count)
median(twi$word_count)


#только эмодзи
mean(twi$count_emojis)
sd(twi$count_emojis)
median(twi$count_emojis)

#слова + эмодзи
mean(twi$emoji_word_count)
sd(twi$emoji_word_count)
median(twi$emoji_word_count)


#TELEGRAM
tg <- df_with_all_emojies %>% filter(source == "Telegram") 
tg <- tg %>% group_by(only_texts, names,time) %>% summarize(count_emojis = n())
tg$word_count <- str_count(tg$only_texts, '\\W+')
tg$emoji_word_count = tg$count_emojis + tg$word_count

mean(tg$word_count)
sd(tg$word_count)
median(tg$word_count)


mean(tg$count_emojis)
sd(tg$count_emojis)
median(tg$count_emojis)


mean(tg$emoji_word_count)
sd(tg$emoji_word_count)
median(tg$emoji_word_count)
```


Графики
```{r}
full_df_twi_tg <- read_csv('full_df_twi_tg.csv')

top_twi <- full_df_twi_tg %>% filter(source=="Twitter")
top_twi <- top_twi %>% group_by(emoji) %>% tally()
top_twi10 <- top_twi %>% top_n(10)
top_twi10 <- arrange(top_twi10, n)

ggplot(data = top_twi10, aes(x = reorder(emoji, -n), y = n))+
  geom_bar(stat = 'identity', fill = 'dodgerblue4') + theme_classic() + ylab("Number of posts (Twitter)") +labs(title = "Top 10 Emojies Twitter")

top_tg <- full_df_twi_tg %>% filter(source=="Telegram")
top_tg <- top_tg %>% group_by(emoji) %>% tally()
top_tg10 <- top_tg %>% top_n(10)
top_tg10 <- arrange(top_tg10, n)

ggplot(data = top_tg10, aes(x = reorder(emoji, -n), y = n))+
  geom_bar(stat = 'identity', fill = 'dodgerblue4') + theme_classic() + ylab("Number of messages (Telegram") + labs (title = "Top 10 Emojies Telegram")

```
